### ISSUE TITLE
Error: ofxAddonLib.props was not found

### ISSUE THREAD

**Issue by k3nnywilliam** [elliotwoods/ofxSpout#3]
When compiling the sender example, I received this error:

Error MSB4019: The imported project "D:\of_v0.9.0_vs_release\addons\ofxAddonLib\ofxAddonLib.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Same error for receiver example too.

**Comment by elliotwoods** [comment]
you need github.com/elliotwoods/ofxAddonLib in your addons folder

**Comment by elliotwoods** [comment]
http://github.com/elliotwoods/ofxAddonLib 
this addon

**Comment by k3nnywilliam** [comment]
thanks Elliot!

**Comment by elliotwoods** [comment]
it works?

**Comment by k3nnywilliam** [comment]
Yep, works fine.

**Comment by elliotwoods** [comment]
I added it to the readme
