### ISSUE TITLE
Receiver texture not drawn

### ISSUE THREAD

**Issue by mruegenberg** [elliotwoods/ofxSpout#4]
The receiver texture example always only shows a blank screen. Choosing different sources etc doesn't help.

I'm not sure how to debug this, but it works in [ofxSpout by Mat-Loz](https://github.com/Mat-Loz/ofxSpout). (I would much prefer your API though.) 

Also, the texture size comes through correctly in the receiver and drawing other objects in `ofApp::draw()` also works. Allocating the texture manually doesn't help.

I'm on Windows 8.1, oF 0.9.3, Quadro K5200.

**Comment by msf567** [comment]
Did you ever fix this? I have the same issue.

**Comment by mruegenberg** [comment]
I decided to extend [ofxSpout2](https://github.com/Kj1/ofxSpout2) with receiver support (already merged).
It works for me without any problems.
